from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any

from chatbot.calendar.provider import CalendarProvider


class CalendarService:
    """
    Coordinate calendar-related business operations.

    This service converts textual booking dates and times into datetime
    objects, applies booking duration and delegates calendar operations
    to the configured provider.
    """

    DATE_FORMAT = "%d/%m/%Y"
    TIME_FORMAT = "%H:%M"

    def __init__(
        self,
        provider: CalendarProvider,
        default_duration_minutes: int = 60,
    ) -> None:
        if default_duration_minutes <= 0:
            raise ValueError(
                "Default duration must be greater than zero."
            )

        self._provider = provider
        self._default_duration_minutes = (
            default_duration_minutes
        )

    def is_available(
        self,
        *,
        date: str,
        time: str,
        duration_minutes: int | None = None,
    ) -> bool:
        """
        Return whether a textual date and time slot is available.
        """

        start, end = self.build_time_range(
            date=date,
            time=time,
            duration_minutes=duration_minutes,
        )

        return self._provider.is_available(
            start=start,
            end=end,
        )

    def create_booking(
        self,
        *,
        date: str,
        time: str,
        title: str,
        duration_minutes: int | None = None,
        description: str | None = None,
        attendee: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> str:
        """
        Check availability and create a calendar booking.

        Return the identifier generated by the provider.
        """

        start, end = self.build_time_range(
            date=date,
            time=time,
            duration_minutes=duration_minutes,
        )

        if not self._provider.is_available(
            start=start,
            end=end,
        ):
            raise ValueError(
                "Requested booking time is not available."
            )

        return self._provider.create_booking(
            start=start,
            end=end,
            title=title,
            description=description,
            attendee=attendee,
            metadata=metadata,
        )

    def cancel_booking(
        self,
        booking_id: str,
    ) -> None:
        """
        Cancel an existing calendar booking.
        """

        self._provider.cancel_booking(
            booking_id
        )

    def list_bookings(
        self,
        *,
        start: datetime,
        end: datetime,
    ) -> list[dict[str, Any]]:
        """
        Return calendar bookings overlapping the requested range.
        """

        return self._provider.list_bookings(
            start=start,
            end=end,
        )

    def build_time_range(
        self,
        *,
        date: str,
        time: str,
        duration_minutes: int | None = None,
    ) -> tuple[datetime, datetime]:
        """
        Convert textual date and time values into a datetime range.
        """

        duration = self._resolve_duration(
            duration_minutes
        )

        start = self.parse_datetime(
            date=date,
            time=time,
        )

        end = start + timedelta(
            minutes=duration
        )

        return start, end

    @classmethod
    def parse_datetime(
        cls,
        *,
        date: str,
        time: str,
    ) -> datetime:
        """
        Parse DD/MM/YYYY and HH:MM values into a datetime.
        """

        normalized_date = date.strip()
        normalized_time = time.strip()

        raw_datetime = (
            f"{normalized_date} "
            f"{normalized_time}"
        )

        try:
            return datetime.strptime(
                raw_datetime,
                (
                    f"{cls.DATE_FORMAT} "
                    f"{cls.TIME_FORMAT}"
                ),
            )
        except ValueError as exc:
            raise ValueError(
                "Calendar date and time must use "
                "DD/MM/YYYY and HH:MM formats."
            ) from exc

    def _resolve_duration(
        self,
        duration_minutes: int | None,
    ) -> int:
        duration = (
            self._default_duration_minutes
            if duration_minutes is None
            else duration_minutes
        )

        if duration <= 0:
            raise ValueError(
                "Duration must be greater than zero."
            )

        return duration