from __future__ import annotations

from datetime import date, datetime, timedelta
from typing import Any

from chatbot.availability import (
    AvailabilityService,
    BusyPeriod,
    BookingRules,
    BusinessHours,
    TimeSlot,
)
from chatbot.calendar.availability_adapter import (
    CalendarAvailabilityAdapter,
)
from chatbot.calendar.provider import CalendarProvider

from zoneinfo import ZoneInfo

class CalendarService:
    """
    Coordinate calendar-related business operations.

    This service converts textual booking dates and times into datetime
    objects, applies booking duration and delegates calendar operations
    to the configured provider.
    """

    DATE_FORMAT = "%d/%m/%Y"
    TIME_FORMAT = "%H:%M"

    def __init__(
        self,
        provider: CalendarProvider,
        default_duration_minutes: int = 60,
        availability_adapter: (
            CalendarAvailabilityAdapter | None
        ) = None,
        availability_service: (
            AvailabilityService | None
        ) = None,
    ) -> None:
        if default_duration_minutes <= 0:
            raise ValueError(
                "Default duration must be greater than zero."
            )

        self._provider = provider
        self._default_duration_minutes = (
            default_duration_minutes
        )
        self._availability_adapter = (
            availability_adapter
            or CalendarAvailabilityAdapter()
        )
        self._availability_service = (
            availability_service
            or AvailabilityService()
        )

    def is_available(
        self,
        *,
        date: str,
        time: str,
        duration_minutes: int | None = None,
    ) -> bool:
        """
        Return whether a textual date and time slot is available.
        """

        start, end = self.build_time_range(
            date=date,
            time=time,
            duration_minutes=duration_minutes,
        )

        return self._provider.is_available(
            start=start,
            end=end,
        )

    def create_booking(
        self,
        *,
        date: str,
        time: str,
        title: str,
        duration_minutes: int | None = None,
        description: str | None = None,
        attendee: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> str:
        """
        Check availability and create a calendar booking.

        Return the identifier generated by the provider.
        """

        start, end = self.build_time_range(
            date=date,
            time=time,
            duration_minutes=duration_minutes,
        )

        if not self._provider.is_available(
            start=start,
            end=end,
        ):
            raise ValueError(
                "Requested booking time is not available."
            )

        return self._provider.create_booking(
            start=start,
            end=end,
            title=title,
            description=description,
            attendee=attendee,
            metadata=metadata,
        )

    def reschedule_booking(
        self,
        booking_id: str,
        *,
        date: str,
        time: str,
        duration_minutes: int | None = None,
    ) -> None:
        """
        Check availability and move an existing calendar booking.
        """

        start, end = self.build_time_range(
            date=date,
            time=time,
            duration_minutes=duration_minutes,
        )

        if not self._provider.is_available(
            start=start,
            end=end,
        ):
            raise ValueError(
                "Requested booking time is not available."
            )

        self._provider.reschedule_booking(
            booking_id,
            start=start,
            end=end,
        )

    def cancel_booking(
        self,
        booking_id: str,
    ) -> None:
        """
        Cancel an existing calendar booking.
        """

        self._provider.cancel_booking(
            booking_id
        )

    def list_bookings(
        self,
        *,
        start: datetime,
        end: datetime,
    ) -> list[dict[str, Any]]:
        """
        Return calendar bookings overlapping the requested range.
        """

        return self._provider.list_bookings(
            start=start,
            end=end,
        )

    def build_time_range(
        self,
        *,
        date: str,
        time: str,
        duration_minutes: int | None = None,
    ) -> tuple[datetime, datetime]:
        """
        Convert textual date and time values into a datetime range.
        """

        duration = self._resolve_duration(
            duration_minutes
        )

        start = self.parse_datetime(
            date=date,
            time=time,
        )

        end = start + timedelta(
            minutes=duration
        )

        return start, end

    @classmethod
    def parse_datetime(
        cls,
        *,
        date: str,
        time: str,
    ) -> datetime:
        """
        Parse DD/MM/YYYY and HH:MM values into a datetime.
        """

        normalized_date = date.strip()
        normalized_time = time.strip()

        raw_datetime = (
            f"{normalized_date} "
            f"{normalized_time}"
        )

        try:
            return datetime.strptime(
                raw_datetime,
                (
                    f"{cls.DATE_FORMAT} "
                    f"{cls.TIME_FORMAT}"
                ),
            )
        except ValueError as exc:
            raise ValueError(
                "Calendar date and time must use "
                "DD/MM/YYYY and HH:MM formats."
            ) from exc

    def _resolve_duration(
        self,
        duration_minutes: int | None,
    ) -> int:
        duration = (
            self._default_duration_minutes
            if duration_minutes is None
            else duration_minutes
        )

        if duration <= 0:
            raise ValueError(
                "Duration must be greater than zero."
            )

        return duration

    def get_busy_periods(
        self,
        start: datetime,
        end: datetime,
    ) -> tuple[BusyPeriod, ...]:
        self._validate_aware_window(
            start,
            end,
        )

        events = self._provider.list_bookings(
            start=start,
            end=end,
        )

        return (
            self._availability_adapter
            .events_to_busy_periods(events)
        )

    def get_available_slots_for_date(
        self,
        target_date: date,
        *,
        business_hours: BusinessHours,
        rules: BookingRules,
        now: datetime,
    ) -> tuple[TimeSlot, ...]:
        """
        Return available booking slots for a date,
        including existing calendar bookings.
        """

        working_ranges = business_hours.hours_for_date(
            target_date
        )

        if not working_ranges:
            return ()

        timezone = ZoneInfo(
            business_hours.timezone_name
        )

        window_start = datetime.combine(
            target_date,
            working_ranges[0].start,
            tzinfo=timezone,
        )

        window_end = datetime.combine(
            target_date,
            working_ranges[-1].end,
            tzinfo=timezone,
        )

        busy_periods = self.get_busy_periods(
            window_start,
            window_end,
        )

        return (
            self._availability_service
            .get_available_slots_for_date(
                target_date,
                business_hours=business_hours,
                rules=rules,
                busy_periods=busy_periods,
                now=now,
            )
        )

    def get_available_dates(
        self,
        *,
        start_date: date,
        days: int,
        business_hours: BusinessHours,
        rules: BookingRules,
        now: datetime,
    ) -> tuple[date, ...]:
        """
        Return dates that contain at least one available booking slot.
        """

        if days <= 0:
            raise ValueError(
                "Days must be greater than zero."
            )

        available_dates: list[date] = []

        for offset in range(days):
            target_date = start_date + timedelta(
                days=offset,
            )

            available_slots = (
                self.get_available_slots_for_date(
                    target_date,
                    business_hours=business_hours,
                    rules=rules,
                    now=now,
                )
            )

            if available_slots:
                available_dates.append(
                    target_date
                )

        return tuple(
            available_dates
        )

    @staticmethod
    def _validate_aware_window(
        start: datetime,
        end: datetime,
    ) -> None:
        values = (
            start,
            end,
        )

        if any(
            value.tzinfo is None
            or value.utcoffset() is None
            for value in values
        ):
            raise ValueError(
                "Calendar window datetimes must be "
                "timezone-aware."
            )

        if end <= start:
            raise ValueError(
                "Calendar window end must be later "
                "than start."
            )

    