# chatbot/core/states.py

MAIN_MENU = "MAIN_MENU"

VIEW_SESSIONS = "VIEW_SESSIONS"
VIEW_PRICES = "VIEW_PRICES"
VIEW_DATES = "VIEW_DATES"

BOOKING_SESSION_SELECTION = "BOOKING_SESSION_SELECTION"
BOOKING_DATE_SELECTION = "BOOKING_DATE_SELECTION"
BOOKING_CONFIRMATION = "BOOKING_CONFIRMATION"

HUMAN_SUPPORT = "HUMAN_SUPPORT"